### ISSUE TITLE
My laravel version is 6.0 but not install this package

### ISSUE THREAD

**Issue by hiteshdevaiya** [jackbayliss/laravel-dhl-api#1]
i have laravel version 6.0 and i upgrade 5.4 to 6.0
when install this package i got this error

error : [InvalidArgumentException]
  Could not find a version of package jackbayliss/laravel-dhl-api matching your minimum-stability (stable). Require i
  t with an explicit version constraint allowing its desired stability.
  
 can you help please?

**Comment by jackbayliss** [comment]
This is now fixed, apologies for the super late response- must of missed it.
